/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Timesheet
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultTaskNumberPatterns: "",
  roundUpTime: false,
  timeRoundingInterval: 15,
  stripMarkdown: false,
  templateHeader: "> [!summary] Timesheet {tasksDuration}",
  templateDuration: "({duration})",
  templateTask: "> \n> {taskNumber} {taskDuration}",
  templateTaskLog: "> - {taskLogTitle}",
  templateFooter: ""
};
var TimesheetSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Default task number patterns").setDesc(
      "You can specify task number patterns in a timesheet code block (one pattern per line), or set default patterns here \u2014 they will apply to all timesheet code blocks that don't have patterns specified."
    ).setClass("text-snippets-class").addTextArea(
      (text) => text.setValue(this.plugin.settings.defaultTaskNumberPatterns).onChange(async (value) => {
        this.plugin.settings.defaultTaskNumberPatterns = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Time rounding").setHeading();
    new import_obsidian.Setting(containerEl).setName("Round up time").setDesc(
      "Enables time rounding for tasks, so that, for example, 3h 42m is displayed as 4h."
    ).addToggle(
      (text) => text.setValue(this.plugin.settings.roundUpTime).onChange(async (value) => {
        this.plugin.settings.roundUpTime = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Time rounding interval").setDesc(
      "The interval to which a task's time will be rounded. For example, if the interval is 30m, then 2h 5m will be displayed as 2h 30m."
    ).addDropdown(
      (text) => text.addOptions({
        "15": "15m",
        "30": "30m",
        "60": "1h"
      }).setValue(this.plugin.settings.timeRoundingInterval.toString()).onChange(async (value) => {
        this.plugin.settings.timeRoundingInterval = Number(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Output").setHeading();
    new import_obsidian.Setting(containerEl).setName("Remove Markdown formatting").setDesc(
      "Removes Markdown formatting from task numbers and task log titles while preserving the Markdown used by the output templates."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.stripMarkdown).onChange(async (value) => {
        this.plugin.settings.stripMarkdown = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Templates").setHeading();
    new import_obsidian.Setting(containerEl).setName("Duration").setDesc(
      "Macros: {duration} \u2014 duration presentation (for example: 1h 30m)."
    ).setClass("text-snippets-class").addTextArea(
      (text) => text.setValue(this.plugin.settings.templateDuration).onChange(async (value) => {
        this.plugin.settings.templateDuration = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Header").setDesc(
      "Macros: {tasksDuration} \u2014 total duration of all tasks in a note."
    ).setClass("text-snippets-class").addTextArea(
      (text) => text.setValue(this.plugin.settings.templateHeader).onChange(async (value) => {
        this.plugin.settings.templateHeader = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Task").setDesc(
      "Macros: {taskNumber} \u2014 number of a task, {taskDuration} \u2014 total duration of a task."
    ).setClass("text-snippets-class").addTextArea(
      (text) => text.setValue(this.plugin.settings.templateTask).onChange(async (value) => {
        this.plugin.settings.templateTask = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Task log").setDesc(
      "Macros: {taskLogTitle} \u2014 prettified task log title."
    ).setClass("text-snippets-class").addTextArea(
      (text) => text.setValue(this.plugin.settings.templateTaskLog).onChange(async (value) => {
        this.plugin.settings.templateTaskLog = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Footer").setDesc(
      "No macros."
    ).setClass("text-snippets-class").addTextArea(
      (text) => text.setValue(this.plugin.settings.templateFooter).onChange(async (value) => {
        this.plugin.settings.templateFooter = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/codeblocks/timesheet.ts
var import_obsidian3 = require("obsidian");

// src/parser.ts
var import_obsidian2 = require("obsidian");
var TimeLogsParser = class {
  static timeLogs(text, taskNumberPatterns) {
    const result = [];
    const regexp = /^- \[.\] \s*(.*)$/gm;
    let match;
    while ((match = regexp.exec(text)) !== null) {
      const timeLog = this.getTimeLog(match[1], taskNumberPatterns);
      if (timeLog !== void 0) {
        result.push(timeLog);
      }
    }
    return result;
  }
  static getPeriod(title) {
    const regexp = /^((\d{1,2}:\d{1,2})\s*-\s*(\d{1,2}:\d{1,2})).*$/gm;
    let match;
    const result = {
      "startTime": "00:00",
      "endTime": "00:00",
      "string": ""
    };
    if ((match = regexp.exec(title.trim())) !== null) {
      result.startTime = match[2];
      result.endTime = match[3];
      result.string = match[1];
    }
    return result;
  }
  static getTimeLog(title, taskNumberPatterns) {
    const period = this.getPeriod(title);
    const start = (0, import_obsidian2.moment)(period.startTime, "HH:mm");
    let end = (0, import_obsidian2.moment)(period.endTime, "HH:mm");
    if (end.isBefore(start)) {
      end = end.add(1, "day");
    }
    const durationMs = end.diff(start);
    const taskNumber = this.getTaskNumber(title, taskNumberPatterns);
    if (durationMs > 0 || taskNumber !== "") {
      return {
        taskNumber,
        interval: `${start.format("HH:mm")}-${end.format("HH:mm")}`,
        intervalString: period.string,
        duration: durationMs,
        title: title.trim()
      };
    }
    return void 0;
  }
  static getTaskNumber(title, taskNumberPatterns) {
    let taskNumber = "";
    taskNumberPatterns.every((taskNumberPattern) => {
      const match = new RegExp(taskNumberPattern, "gm").exec(title);
      if (match !== null) {
        taskNumber = match[0];
        return false;
      }
      return true;
    });
    return taskNumber;
  }
  static getTimestamp(time) {
    return Date.parse(`0001-01-01 ${time}`);
  }
};

// src/codeblocks/timesheet.ts
var TimesheetCodeBlock = class {
  static async render(plugin, src, body, ctx) {
    const noteFile = plugin.app.vault.getFileByPath(ctx.sourcePath);
    if (noteFile != null) {
      const taskNumberPatterns = this.getTaskNumberPatterns(src, plugin);
      const noteText = await plugin.app.vault.read(noteFile);
      const timeLogs = TimeLogsParser.timeLogs(noteText, taskNumberPatterns);
      const tasks = [];
      timeLogs.filter((timeLog) => timeLog.taskNumber !== "").forEach((timeLog) => {
        let task = tasks.find((task2) => task2.number == timeLog.taskNumber);
        if (task !== void 0) {
          task.timeLogs.push(timeLog);
          task.duration += timeLog.duration;
        } else {
          task = {
            timeLogs: [timeLog],
            duration: timeLog.duration,
            number: timeLog.taskNumber
          };
          tasks.push(task);
        }
      });
      tasks.sort((a, b) => a.duration > b.duration ? -1 : 1);
      if (plugin.settings.roundUpTime) {
        tasks.forEach((task, taskIndex) => {
          tasks[taskIndex].duration = this.roundTaskDuration(plugin, task.duration);
        });
      }
      let totalDuration = 0;
      tasks.forEach(function(task) {
        totalDuration += task.duration;
      });
      const totalDurationPresentation = this.getDurationPresentation(plugin, totalDuration);
      const header = plugin.settings.templateHeader ? plugin.settings.templateHeader.replace("{tasksDuration}", totalDurationPresentation) : "";
      const contentLines = [];
      tasks.forEach((task) => {
        if (plugin.settings.templateTask) {
          const taskNumber = plugin.settings.stripMarkdown ? this.stripMarkdown(task.number) : task.number;
          contentLines.push(
            plugin.settings.templateTask.replace("{taskNumber}", taskNumber).replace("{taskDuration}", this.getDurationPresentation(plugin, task.duration))
          );
        }
        if (plugin.settings.templateTaskLog) {
          const logs = [];
          task.timeLogs.forEach((log) => {
            let title = log.title.replace(task.number, "");
            title = title.replace(log.intervalString, "");
            title = title.replace(/\(\s*\)/g, "").trim();
            if (plugin.settings.stripMarkdown) {
              title = this.stripMarkdown(title);
            }
            if (logs.indexOf(title) == -1) {
              contentLines.push(plugin.settings.templateTaskLog.replace("{taskLogTitle}", title));
              logs.push(title);
            }
          });
        }
      });
      const content = contentLines.join("\n");
      let output = header;
      if (content) {
        output = output ? this.joinTemplateSections(output, content) : content;
      }
      if (plugin.settings.templateFooter) {
        output = output ? this.joinTemplateSections(output, plugin.settings.templateFooter) : plugin.settings.templateFooter;
      }
      import_obsidian3.MarkdownRenderer.render(plugin.app, output, body, "", plugin);
    }
  }
  static joinTemplateSections(left, right) {
    const normalizedLeft = left.replace(/(?:\r?\n[ \t]*)+$/, "");
    const normalizedRight = right.replace(/^(?:[ \t]*\r?\n)+/, "");
    if (!normalizedLeft) {
      return normalizedRight;
    }
    if (!normalizedRight) {
      return normalizedLeft;
    }
    return `${normalizedLeft}\n${normalizedRight}`;
  }
  static stripMarkdown(text) {
    let result = text;
    result = result.replace(/!\[\[([^\]]+)\]\]/g, (_match, target) => {
      const separatorIndex = target.lastIndexOf("|");
      return separatorIndex >= 0 ? target.slice(separatorIndex + 1) : target;
    });
    result = result.replace(/\[\[([^\]]+)\]\]/g, (_match, target) => {
      const separatorIndex = target.lastIndexOf("|");
      return separatorIndex >= 0 ? target.slice(separatorIndex + 1) : target;
    });
    result = result.replace(/!\[([^\]]*)\]\((?:\\.|[^)])*\)/g, "$1");
    result = result.replace(/\[([^\]]+)\]\((?:\\.|[^)])*\)/g, "$1");
    result = result.replace(/\[([^\]]+)\]\[[^\]]*\]/g, "$1");
    result = result.replace(/<((?:https?:\/\/|mailto:)[^>]+)>/gi, "$1");
    result = result.replace(/<\/?[A-Za-z][^>]*>/g, "");
    result = result.replace(/(`{1,3})(.*?)\1/g, "$2");
    result = result.replace(/(\*\*|__)(?=\S)([\s\S]*?\S)\1/g, "$2");
    result = result.replace(/(~~|==)(?=\S)([\s\S]*?\S)\1/g, "$2");
    result = result.replace(/\*(?=\S)([\s\S]*?\S)\*/g, "$1");
    result = result.replace(/(?<!\w)_(?=\S)([\s\S]*?\S)_(?!\w)/g, "$1");
    result = result.replace(/\\([\\`*{}\[\]()#+\-.!_|>~])/g, "$1");
    return result.replace(/\s+/g, " ").trim();
  }
  static roundTaskDuration(plugin, duration) {
    let result = duration;
    const interval = plugin.settings.timeRoundingInterval * 60 * 1e3;
    result = Math.ceil(result / interval) * interval;
    return result;
  }
  static getDurationPresentation(plugin, duration) {
    let minutes = duration / 1e3 / 60;
    const hours = Math.floor(minutes / 60);
    minutes -= hours * 60;
    const resultItems = [];
    if (hours > 0) {
      resultItems.push(`${hours}h`);
    }
    if (minutes > 0) {
      resultItems.push(`${minutes}m`);
    }
    let result = resultItems.join(" ");
    if (result && plugin.settings.templateDuration) {
      result = plugin.settings.templateDuration.replace("{duration}", result);
    }
    return result;
  }
  static getTaskNumberPatterns(codeblockText, plugin) {
    let patternsString = codeblockText.trim();
    if (patternsString == "") {
      patternsString = plugin.settings.defaultTaskNumberPatterns;
    }
    return patternsString.split("\n").map((patternString) => patternString.trim());
  }
};

// src/main.ts
var Timesheet = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingsTab();
    this.addInsertTimesheetCommand();
    this.addTimesheetCodeblock();
  }
  async addSettingsTab() {
    this.addSettingTab(new TimesheetSettingTab(this.app, this));
  }
  async addInsertTimesheetCommand() {
    this.addCommand({
      id: "insert-timesheet",
      name: "Insert timesheet",
      editorCallback: (editor, view) => {
        editor.replaceSelection(`\`\`\`timesheet

\`\`\``);
      }
    });
  }
  async addTimesheetCodeblock() {
    this.registerMarkdownCodeBlockProcessor(
      "timesheet",
      async (src, el, ctx) => {
        try {
          const root = el.createEl("div");
          const body = root.createEl("div");
          await TimesheetCodeBlock.render(this, src, body, ctx);
        } catch (error) {
          el.createEl("h3", {
            text: `Failed to show timesheet: ${error.message}`
          });
        }
      }
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */